application: cambridge-lookup-api
version: 1
runtime: go
api_version: go1

handlers:
- url: /configure
  login: admin
  script: _go_app
- url: /.*
  script: _go_app


automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 5000ms
  max_concurrent_requests: 500
